version: 0.2

phases:
  pre_build:
    commands:
      - echo Retrieving DOCKER_USERNAME and DOCKER_PASSWORD from Parameter Store...
      - export DOCKER_USERNAME=$(aws ssm get-parameter --name "/course-catalog/production/DOCKER_USERNAME" --query "Parameter.Value" --output text)
      - export DOCKER_PASSWORD=$(aws ssm get-parameter --name "/course-catalog/production/DOCKER_PASSWORD" --with-decryption --query "Parameter.Value" --output text)
      
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 834549009763.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t learningecs .
      - docker tag learningecs:latest 834549009763.dkr.ecr.us-east-1.amazonaws.com/learningecs:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 834549009763.dkr.ecr.us-east-1.amazonaws.com/learningecs:latest